### ISSUE TITLE
recognizers: 'swipe' fails under fastboot.

### ISSUE THREAD

**Issue by kitsunde** [html-next/ember-gestures#69]
I have a component that renders only if I remove `recognizers: 'swipe'` under fastboot. Full stack trace.

<details>

```bash
There was an error running your app in fastboot. More info about the error:
 ReferenceError: Hammer is not defined
    at Module.callback (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:88837:42)
    at Module.exports (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:132:32)
    at Module.reify (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:153:59)
    at Module.exports (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:130:10)
    at requireModule (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:32:18)
    at Class._extractDefaultExport (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:93871:20)
    at Class.resolveOther (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:93584:32)
    at Class.superWrapper (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:35338:22)
    at Class.resolve (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:16647:35)
    at resolve (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:12979:36)
    at Object.resolve (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:12438:21)
    at Object.resolve (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:12442:55)
    at factoryFor (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:11940:28)
    at Object.lookupFactory (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:11806:14)
    at Class._lookupFactory (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:44867:33)
    at Class.lookupRecognizer (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:89001:66)
    at /home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:88916:22
    at Array.map (native)
    at Class.retrieve (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:88915:28)
    at Class.init (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:88760:55)
    at Class.superWrapper [as init] (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:35338:22)
    at new Class (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:48445:17)
    at Function.create (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:48705:14)
    at createComponent (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:24642:32)
    at Function.ComponentNodeManager_create [as create] (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:24526:17)
    at Object.componentHook [as component] (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:20926:74)
    at handleRedirect (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:55772:21)
    at Object.inline (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:55926:9)
    at Object.inline (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56453:17)
    at RenderResult.populateNodes (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56874:19)
    at RenderResult.render (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56809:10)
    at render (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56618:18)
    at /home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57440:7
    at renderAndCleanup (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57475:18)
    at Block._firstRender (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57437:5)
    at Block.invoke (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57415:12)
    at ViewNodeManager_render_instrument (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:24787:20)
    at Object.instrument (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:26913:23)
    at ViewNodeManager_render [as render] (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:24771:55)
    at Object.render (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:23631:19)
    at handleKeyword (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:55836:17)
    at handleRedirect (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:55783:9)
    at Object.inline (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:55926:9)
    at Object.content (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56462:19)
    at RenderResult.populateNodes (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56876:19)
    at RenderResult.render (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56809:10)
    at render (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56618:18)
    at /home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57440:7
    at renderAndCleanup (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57475:18)
    at Block._firstRender (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57437:5)
    at Block.invoke (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57415:12)
    at yieldKeyword (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:24327:13)
    at handleKeyword (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:55797:14)
    at handleRedirect (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:55783:9)
    at Object.inline (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:55926:9)
    at Object.content (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56462:19)
    at RenderResult.populateNodes (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56876:19)
    at RenderResult.render (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56809:10)
    at render (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56618:18)
    at /home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57440:7
    at renderAndCleanup (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57475:18)
    at Block._firstRender (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57437:5)
    at Block.invoke (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57415:12)
    at ViewNodeManager_render_instrument (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:24787:20)
    at Object.instrument (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:26913:23)
    at ViewNodeManager_render [as render] (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:24771:55)
    at Object.render (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:23631:19)
    at handleKeyword (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:55836:17)
    at handleRedirect (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:55783:9)
    at Object.inline (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:55926:9)
    at Object.content (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56462:19)
    at RenderResult.populateNodes (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56876:19)
    at RenderResult.render (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56809:10)
    at render (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:56618:18)
    at /home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57440:7
    at renderAndCleanup (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57475:18)
    at Block._firstRender (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57437:5)
    at Block.invoke (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:57415:12)
    at ViewNodeManager_render_instrument (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:24787:20)
    at Object.instrument (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:26913:23)
    at ViewNodeManager_render [as render] (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:24771:55)
    at Object.renderHTMLBarsBlock (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:27122:17)
    at Renderer_prerenderTopLevelView [as prerenderTopLevelView] (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:24983:36)
    at Renderer_renderTopLevelView [as renderTopLevelView] (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:24992:12)
    at invokeWithOnError (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:11530:18)
    at Object.flush (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:11587:11)
    at Object.flush (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:11395:17)
    at Object.end (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:10709:25)
    at Object.run (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:10822:18)
    at Object.join (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:10851:25)
    at Function.run.join (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:34303:28)
    at Object.hash.success (/home/deploy/pokemon/local/src/frontend/dist/fastboot/vendor.js:83103:33)
    at fire (/home/deploy/pokemon/local/src/frontend/node_modules/jquery-deferred/lib/jquery-callbacks.js:78:30)
    at Object.fireWith (/home/deploy/pokemon/local/src/frontend/node_modules/jquery-deferred/lib/jquery-callbacks.js:188:7)
    at Object.fire [as resolve] (/home/deploy/pokemon/local/src/frontend/node_modules/jquery-deferred/lib/jquery-callbacks.js:195:10)
    at dataHandler (/home/deploy/pokemon/local/src/frontend/node_modules/najax/lib/najax.js:163:13)
    at IncomingMessage.<anonymous> (/home/deploy/pokemon/local/src/frontend/node_modules/najax/lib/najax.js:194:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

</details>

**Comment by eriktrom** [comment]
Try removing the typeof check here: https://github.com/html-next/ember-gestures/blob/develop/addon/recognizers/swipe.js#L4 - and tell us what u get - replace it with an empty string and give your fastboot setup a whirl

honestly thought this was fixed so thanks for filing the issue

**Comment by eriktrom** [comment]
This should be fixed in most recent npm release. Sorry, it was a release issue.
